export enum BuildingType {
  CRYSTAL_MINE = 'CRYSTAL_MINE',
  DEUTERIUM_SYNTHESIZER = 'DEUTERIUM_SYNTHESIZER',
  METAL_MINE = 'METAL_MINE',
  FUSION_REACTOR = 'FUSION_REACTOR',
  SOLAR_PLANT = 'SOLAR_PLANT',
  SOLAR_SATELLITE = 'SOLAR_SATELLITE',
  CRYSTAL_STORAGE = 'CRYSTAL_STORAGE',
  METAL_STORAGE = 'METAL_STORAGE',
  DEUTERIUM_TANK = 'DEUTERIUM_TANK',
}
